# Generated by Django 4.1.1 on 2022-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='entry_title',
            field=models.CharField(default='Merkintä', max_length=100),
        ),
    ]
